import AnimatePresence from '$lib/components/AnimatePresence.svelte'
import MotionConfig from '$lib/components/MotionConfig.svelte'

export { motion } from '$lib/motion'

// Re-export core animation functions from motion
export { animate, delay, hover, inView, press, resize, scroll, stagger, transform } from 'motion'

// Re-export easing functions
export {
    anticipate,
    backIn,
    backInOut,
    backOut,
    circIn,
    circInOut,
    circOut,
    cubicBezier,
    easeIn,
    easeInOut,
    easeOut
} from 'motion'

// Re-export utility functions
export { clamp, distance, distance2D, interpolate, mix, pipe, progress, wrap } from 'motion'

// Re-export all Motion types so consumers can import types from this package
export type {
    DragAxis,
    DragConstraints,
    DragControls,
    DragInfo,
    DragTransition,
    MotionAnimate,
    MotionInitial,
    MotionOnDirectionLock,
    MotionOnDragTransitionEnd,
    MotionOnInViewEnd,
    MotionOnInViewStart,
    MotionTransition,
    MotionWhileDrag,
    MotionWhileFocus,
    MotionWhileHover,
    MotionWhileInView,
    MotionWhileTap,
    ReducedMotionConfig,
    Variants
} from '$lib/types'
export { useAnimationFrame } from '$lib/utils/animationFrame'
export { useCycle } from '$lib/utils/cycle'
export type { Cycle, CycleState } from '$lib/utils/cycle'
export { createDragControls } from '$lib/utils/dragControls'
export { useMotionTemplate } from '$lib/utils/motionTemplate'
export { useMotionValue } from '$lib/utils/motionValue'
export type { MotionValue } from '$lib/utils/motionValue'
export { useMotionValueEvent } from '$lib/utils/motionValueEvent'
export { useReducedMotion } from '$lib/utils/reducedMotion'
export { useReducedMotionConfig } from '$lib/utils/reducedMotionConfig'
export { useScroll } from '$lib/utils/scroll'
export { useSpring } from '$lib/utils/spring'
export { useVelocity } from '$lib/utils/velocity'
/**
 * @deprecated Use `styleString` instead for reactive styles with automatic unit handling.
 */
export { stringifyStyleObject } from '$lib/utils/styleObject'
export { styleString } from '$lib/utils/styleObject.svelte'
export { useTime } from '$lib/utils/time'
export { useTransform } from '$lib/utils/transform'
export { AnimatePresence, MotionConfig }

// Named component exports — tree-shakeable alternative to the `motion` object
export { default as MotionA } from '$lib/html/A.svelte'
export { default as MotionAbbr } from '$lib/html/Abbr.svelte'
export { default as MotionAddress } from '$lib/html/Address.svelte'
export { default as MotionAnimateElement } from '$lib/html/Animate.svelte'
export { default as MotionAnimatemotion } from '$lib/html/Animatemotion.svelte'
export { default as MotionAnimatetransform } from '$lib/html/Animatetransform.svelte'
export { default as MotionArea } from '$lib/html/Area.svelte'
export { default as MotionArticle } from '$lib/html/Article.svelte'
export { default as MotionAside } from '$lib/html/Aside.svelte'
export { default as MotionAudio } from '$lib/html/Audio.svelte'
export { default as MotionB } from '$lib/html/B.svelte'
export { default as MotionBase } from '$lib/html/Base.svelte'
export { default as MotionBdi } from '$lib/html/Bdi.svelte'
export { default as MotionBdo } from '$lib/html/Bdo.svelte'
export { default as MotionBlockquote } from '$lib/html/Blockquote.svelte'
export { default as MotionBr } from '$lib/html/Br.svelte'
export { default as MotionButton } from '$lib/html/Button.svelte'
export { default as MotionCanvas } from '$lib/html/Canvas.svelte'
export { default as MotionCaption } from '$lib/html/Caption.svelte'
export { default as MotionCircle } from '$lib/html/Circle.svelte'
export { default as MotionCite } from '$lib/html/Cite.svelte'
export { default as MotionClippath } from '$lib/html/Clippath.svelte'
export { default as MotionCode } from '$lib/html/Code.svelte'
export { default as MotionCol } from '$lib/html/Col.svelte'
export { default as MotionColgroup } from '$lib/html/Colgroup.svelte'
export { default as MotionCursor } from '$lib/html/Cursor.svelte'
export { default as MotionData } from '$lib/html/Data.svelte'
export { default as MotionDatalist } from '$lib/html/Datalist.svelte'
export { default as MotionDd } from '$lib/html/Dd.svelte'
export { default as MotionDefs } from '$lib/html/Defs.svelte'
export { default as MotionDel } from '$lib/html/Del.svelte'
export { default as MotionDesc } from '$lib/html/Desc.svelte'
export { default as MotionDetails } from '$lib/html/Details.svelte'
export { default as MotionDfn } from '$lib/html/Dfn.svelte'
export { default as MotionDialog } from '$lib/html/Dialog.svelte'
export { default as MotionDiv } from '$lib/html/Div.svelte'
export { default as MotionDl } from '$lib/html/Dl.svelte'
export { default as MotionDt } from '$lib/html/Dt.svelte'
export { default as MotionEllipse } from '$lib/html/Ellipse.svelte'
export { default as MotionEm } from '$lib/html/Em.svelte'
export { default as MotionEmbed } from '$lib/html/Embed.svelte'
export { default as MotionFeblend } from '$lib/html/Feblend.svelte'
export { default as MotionFecolormatrix } from '$lib/html/Fecolormatrix.svelte'
export { default as MotionFecomponenttransfer } from '$lib/html/Fecomponenttransfer.svelte'
export { default as MotionFecomposite } from '$lib/html/Fecomposite.svelte'
export { default as MotionFeconvolvematrix } from '$lib/html/Feconvolvematrix.svelte'
export { default as MotionFediffuselighting } from '$lib/html/Fediffuselighting.svelte'
export { default as MotionFedisplacementmap } from '$lib/html/Fedisplacementmap.svelte'
export { default as MotionFedistantlight } from '$lib/html/Fedistantlight.svelte'
export { default as MotionFeflood } from '$lib/html/Feflood.svelte'
export { default as MotionFefunca } from '$lib/html/Fefunca.svelte'
export { default as MotionFefuncb } from '$lib/html/Fefuncb.svelte'
export { default as MotionFefuncg } from '$lib/html/Fefuncg.svelte'
export { default as MotionFefuncr } from '$lib/html/Fefuncr.svelte'
export { default as MotionFegaussianblur } from '$lib/html/Fegaussianblur.svelte'
export { default as MotionFeimage } from '$lib/html/Feimage.svelte'
export { default as MotionFemerge } from '$lib/html/Femerge.svelte'
export { default as MotionFemergenode } from '$lib/html/Femergenode.svelte'
export { default as MotionFemorphology } from '$lib/html/Femorphology.svelte'
export { default as MotionFeoffset } from '$lib/html/Feoffset.svelte'
export { default as MotionFepointlight } from '$lib/html/Fepointlight.svelte'
export { default as MotionFespecularlighting } from '$lib/html/Fespecularlighting.svelte'
export { default as MotionFespotlight } from '$lib/html/Fespotlight.svelte'
export { default as MotionFetile } from '$lib/html/Fetile.svelte'
export { default as MotionFeturbulence } from '$lib/html/Feturbulence.svelte'
export { default as MotionFieldset } from '$lib/html/Fieldset.svelte'
export { default as MotionFigcaption } from '$lib/html/Figcaption.svelte'
export { default as MotionFigure } from '$lib/html/Figure.svelte'
export { default as MotionFilter } from '$lib/html/Filter.svelte'
export { default as MotionFooter } from '$lib/html/Footer.svelte'
export { default as MotionForeignobject } from '$lib/html/Foreignobject.svelte'
export { default as MotionForm } from '$lib/html/Form.svelte'
export { default as MotionG } from '$lib/html/G.svelte'
export { default as MotionH1 } from '$lib/html/H1.svelte'
export { default as MotionH2 } from '$lib/html/H2.svelte'
export { default as MotionH3 } from '$lib/html/H3.svelte'
export { default as MotionH4 } from '$lib/html/H4.svelte'
export { default as MotionH5 } from '$lib/html/H5.svelte'
export { default as MotionH6 } from '$lib/html/H6.svelte'
export { default as MotionHeader } from '$lib/html/Header.svelte'
export { default as MotionHgroup } from '$lib/html/Hgroup.svelte'
export { default as MotionHr } from '$lib/html/Hr.svelte'
export { default as MotionI } from '$lib/html/I.svelte'
export { default as MotionIframe } from '$lib/html/Iframe.svelte'
export { default as MotionImage } from '$lib/html/Image.svelte'
export { default as MotionImg } from '$lib/html/Img.svelte'
export { default as MotionInput } from '$lib/html/Input.svelte'
export { default as MotionIns } from '$lib/html/Ins.svelte'
export { default as MotionKbd } from '$lib/html/Kbd.svelte'
export { default as MotionLabel } from '$lib/html/Label.svelte'
export { default as MotionLegend } from '$lib/html/Legend.svelte'
export { default as MotionLi } from '$lib/html/Li.svelte'
export { default as MotionLine } from '$lib/html/Line.svelte'
export { default as MotionLineargradient } from '$lib/html/Lineargradient.svelte'
export { default as MotionMain } from '$lib/html/Main.svelte'
export { default as MotionMap } from '$lib/html/Map.svelte'
export { default as MotionMark } from '$lib/html/Mark.svelte'
export { default as MotionMarker } from '$lib/html/Marker.svelte'
export { default as MotionMask } from '$lib/html/Mask.svelte'
export { default as MotionMath } from '$lib/html/Math.svelte'
export { default as MotionMenu } from '$lib/html/Menu.svelte'
export { default as MotionMetadata } from '$lib/html/Metadata.svelte'
export { default as MotionMeter } from '$lib/html/Meter.svelte'
export { default as MotionMpath } from '$lib/html/Mpath.svelte'
export { default as MotionNav } from '$lib/html/Nav.svelte'
export { default as MotionNoscript } from '$lib/html/Noscript.svelte'
export { default as MotionObject } from '$lib/html/Object.svelte'
export { default as MotionOl } from '$lib/html/Ol.svelte'
export { default as MotionOptgroup } from '$lib/html/Optgroup.svelte'
export { default as MotionOption } from '$lib/html/Option.svelte'
export { default as MotionOutput } from '$lib/html/Output.svelte'
export { default as MotionP } from '$lib/html/P.svelte'
export { default as MotionPath } from '$lib/html/Path.svelte'
export { default as MotionPattern } from '$lib/html/Pattern.svelte'
export { default as MotionPicture } from '$lib/html/Picture.svelte'
export { default as MotionPolygon } from '$lib/html/Polygon.svelte'
export { default as MotionPolyline } from '$lib/html/Polyline.svelte'
export { default as MotionPre } from '$lib/html/Pre.svelte'
export { default as MotionProgress } from '$lib/html/Progress.svelte'
export { default as MotionQ } from '$lib/html/Q.svelte'
export { default as MotionRadialgradient } from '$lib/html/Radialgradient.svelte'
export { default as MotionRect } from '$lib/html/Rect.svelte'
export { default as MotionRp } from '$lib/html/Rp.svelte'
export { default as MotionRt } from '$lib/html/Rt.svelte'
export { default as MotionRuby } from '$lib/html/Ruby.svelte'
export { default as MotionS } from '$lib/html/S.svelte'
export { default as MotionSamp } from '$lib/html/Samp.svelte'
export { default as MotionScript } from '$lib/html/Script.svelte'
export { default as MotionSearch } from '$lib/html/Search.svelte'
export { default as MotionSection } from '$lib/html/Section.svelte'
export { default as MotionSelect } from '$lib/html/Select.svelte'
export { default as MotionSelectedcontent } from '$lib/html/Selectedcontent.svelte'
export { default as MotionSet } from '$lib/html/Set.svelte'
export { default as MotionSlot } from '$lib/html/Slot.svelte'
export { default as MotionSmall } from '$lib/html/Small.svelte'
export { default as MotionSource } from '$lib/html/Source.svelte'
export { default as MotionSpan } from '$lib/html/Span.svelte'
export { default as MotionStop } from '$lib/html/Stop.svelte'
export { default as MotionStrong } from '$lib/html/Strong.svelte'
export { default as MotionStyle } from '$lib/html/Style.svelte'
export { default as MotionSub } from '$lib/html/Sub.svelte'
export { default as MotionSummary } from '$lib/html/Summary.svelte'
export { default as MotionSup } from '$lib/html/Sup.svelte'
export { default as MotionSvg } from '$lib/html/Svg.svelte'
export { default as MotionSwitch } from '$lib/html/Switch.svelte'
export { default as MotionSymbol } from '$lib/html/Symbol.svelte'
export { default as MotionTable } from '$lib/html/Table.svelte'
export { default as MotionTbody } from '$lib/html/Tbody.svelte'
export { default as MotionTd } from '$lib/html/Td.svelte'
export { default as MotionTemplate } from '$lib/html/Template.svelte'
export { default as MotionText } from '$lib/html/Text.svelte'
export { default as MotionTextarea } from '$lib/html/Textarea.svelte'
export { default as MotionTextpath } from '$lib/html/Textpath.svelte'
export { default as MotionTfoot } from '$lib/html/Tfoot.svelte'
export { default as MotionTh } from '$lib/html/Th.svelte'
export { default as MotionThead } from '$lib/html/Thead.svelte'
export { default as MotionTime } from '$lib/html/Time.svelte'
export { default as MotionTitle } from '$lib/html/Title.svelte'
export { default as MotionTr } from '$lib/html/Tr.svelte'
export { default as MotionTrack } from '$lib/html/Track.svelte'
export { default as MotionTref } from '$lib/html/Tref.svelte'
export { default as MotionTspan } from '$lib/html/Tspan.svelte'
export { default as MotionU } from '$lib/html/U.svelte'
export { default as MotionUl } from '$lib/html/Ul.svelte'
export { default as MotionUse } from '$lib/html/Use.svelte'
export { default as MotionVar } from '$lib/html/Var.svelte'
export { default as MotionVideo } from '$lib/html/Video.svelte'
export { default as MotionView } from '$lib/html/View.svelte'
export { default as MotionWbr } from '$lib/html/Wbr.svelte'
