import { isMotionValue, type MotionValue } from 'motion-dom'

/**
 * Structural MotionValue shape accepted by object-form styles.
 *
 * The public API intentionally stays structural because Svelte Motion wraps
 * and augments MotionValues while preserving Motion's runtime contract.
 */
export type MotionStyleMotionValue = {
    /** Read the current style value. */
    get: () => string | number
}

/**
 * A value accepted inside Motion's object-form `style` prop.
 *
 * Static values are serialized into the rendered inline style. MotionValues
 * are also serialized with their current value, then subscribed with
 * `motion-dom`'s `styleEffect` so they can update the DOM without rerenders.
 */
export type MotionStyleValue = string | number | MotionStyleMotionValue | null | undefined

/**
 * React-style object form for the `style` prop.
 *
 * Supports normal CSS properties, CSS variables, and Motion transform
 * shortcuts like `x`, `y`, `scale`, and `rotate`.
 */
export type MotionStyle = Record<string, MotionStyleValue>

/**
 * Customizes the final CSS `transform` string generated from Motion transform
 * shortcuts.
 *
 * @param transform Latest transform shortcut values with CSS units applied.
 * @param generatedTransform The transform string generated by Motion.
 * @returns The transform string to write to the element.
 *
 * @example
 * ```ts
 * const template: TransformTemplate = ({ x }, generated) =>
 *     `translateY(${x}) ${generated}`
 * ```
 */
export type TransformTemplate = (
    transform: Record<string, string | number>,
    generatedTransform: string
) => string

type MergeInlineStylesOptions = {
    preserveTransformDefaults?: boolean
}

const transformPropOrder = [
    'transformPerspective',
    'x',
    'y',
    'z',
    'translateX',
    'translateY',
    'translateZ',
    'scale',
    'scaleX',
    'scaleY',
    'rotate',
    'rotateX',
    'rotateY',
    'rotateZ',
    'skew',
    'skewX',
    'skewY'
] as const

const transformAliases: Partial<Record<(typeof transformPropOrder)[number], string>> = {
    transformPerspective: 'perspective',
    x: 'translateX',
    y: 'translateY',
    z: 'translateZ'
}

const transformProps = new Set<string>(transformPropOrder)

const unitForTransform = (key: string, value: unknown): string => {
    if (key.startsWith('scale')) return ''
    if (typeof value !== 'number') return ''
    if (
        key === 'x' ||
        key === 'y' ||
        key === 'z' ||
        key === 'translateX' ||
        key === 'translateY' ||
        key === 'translateZ' ||
        key === 'transformPerspective'
    ) {
        return 'px'
    }
    return 'deg'
}

const isDefaultTransformValue = (key: string, value: string | number): boolean => {
    const parsed = typeof value === 'number' ? value : Number.parseFloat(value)
    return key.startsWith('scale') ? parsed === 1 : parsed === 0
}

/**
 * Merge inline CSS styles from an existing style string with a Motion initial definition.
 * This is used during SSR to reflect the initial state in server-rendered markup.
 * When `existingStyle` already contains a `transform` and no `initial` or
 * `animateFallback` target is available, `transformTemplate` is not applied so
 * the authored inline transform is preserved.
 *
 * @param existingStyle The consumer-provided inline style string to merge into.
 * @param initial The Motion `initial` target used as the preferred style source.
 * @param animateFallback The Motion `animate` target used when `initial` is empty.
 * @param transformTemplate Optional callback that receives the latest
 *   transform-related values and generated transform string, then returns the
 *   final CSS transform string.
 * @param options Serialization options for specialized animation setup paths.
 * @returns Inline CSS suitable for Svelte's `style` attribute.
 * @example
 * ```ts
 * mergeInlineStyles('color: red', { x: 20 }, null)
 * // => 'color: red; transform: translateX(20px)'
 * ```
 */
export const mergeInlineStyles = (
    existingStyle: unknown,
    initial: Record<string, unknown> | null | undefined,
    animateFallback?: Record<string, unknown> | null | undefined,
    transformTemplate?: TransformTemplate,
    options: MergeInlineStylesOptions = {}
): string => {
    const base: Record<string, string> = parseStyleString(
        typeof existingStyle === 'string' ? existingStyle : ''
    )

    const source = initial && Object.keys(initial).length > 0 ? initial : (animateFallback ?? null)
    if (!source) {
        if (transformTemplate && !base.transform) {
            const templatedTransform = transformTemplate({}, '')
            if (templatedTransform) {
                base.transform = templatedTransform
            }
        }

        return stringifyStyleObject(base)
    }

    const transformParts: string[] = []
    const transformValues: Record<string, string | number> = {}
    const transformPartsByKey: Record<string, string> = {}
    let explicitTransform: string | null = null

    const setProp = (cssProp: string, value: unknown) => {
        if (value == null) return
        const v = Array.isArray(value) ? value[0] : value
        if (v == null) return
        base[cssProp] = String(v)
    }

    const setPx = (cssProp: string, value: unknown) => {
        if (value == null) return
        const v = Array.isArray(value) ? value[0] : value
        if (v == null) return
        base[cssProp] = typeof v === 'number' ? `${v}px` : String(v)
    }

    const addTransform = (key: string, value: unknown) => {
        if (value == null) return
        const v = Array.isArray(value) ? value[0] : value
        if (v == null) return
        const val = typeof v === 'number' ? `${v}${unitForTransform(key, v)}` : String(v)
        transformValues[key] = val
        if (options.preserveTransformDefaults || !isDefaultTransformValue(key, val)) {
            const fn = transformAliases[key as (typeof transformPropOrder)[number]] ?? key
            transformPartsByKey[key] = `${fn}(${val})`
        }
    }

    for (const key of Object.keys(source)) {
        const value = (source as Record<string, unknown>)[key]
        if (transformProps.has(key)) {
            addTransform(key, value)
            continue
        }

        switch (key) {
            case 'opacity':
                setProp('opacity', value)
                break
            case 'backgroundColor':
                setProp('background-color', value)
                break
            case 'borderRadius':
                setProp('border-radius', value)
                break
            case 'width':
                setPx('width', value)
                break
            case 'height':
                setPx('height', value)
                break
            case 'transform':
                explicitTransform = String(Array.isArray(value) ? value[0] : value)
                setProp('transform', value)
                break
            case 'pointerEvents':
                base['pointer-events'] = String(Array.isArray(value) ? value[0] : value)
                break
            case 'cursor':
                setProp('cursor', value)
                break
            // Skip SVG path animation properties - they'll be set by animate()
            case 'pathLength':
            case 'pathOffset':
            case 'pathSpacing':
            case 'strokeDasharray':
            case 'stroke-dasharray':
            case 'strokeDashoffset':
            case 'stroke-dashoffset':
                // Don't add these to inline styles - they interfere with animation
                break
            default:
                // Fallback: write raw as-is for simple CSS props
                if (typeof value === 'string' || typeof value === 'number') {
                    base[toKebabCase(key)] = String(value)
                }
                break
        }
    }

    for (const key of transformPropOrder) {
        const transformPart = transformPartsByKey[key]
        if (transformPart) transformParts.push(transformPart)
    }

    const generatedTransform =
        transformParts.length > 0 ? transformParts.join(' ') : (explicitTransform ?? '')
    if (transformTemplate) {
        const templatedTransform = transformTemplate(transformValues, generatedTransform)
        if (templatedTransform) {
            base['transform'] = templatedTransform
        } else {
            delete base['transform']
        }
    } else if (generatedTransform) {
        base['transform'] = generatedTransform
    }

    return stringifyStyleObject(base)
}

/**
 * Extract the user-authored `transform` declaration from a `style` prop.
 *
 * Used by the projection system as the "base" transform a node resets to
 * while measuring — the value the user wrote, independent of any
 * motion-applied transform (`initial`/`animate`/FLIP/drag) that lands on
 * `element.style.transform` after mount. Reading it from the `style` prop
 * rather than the live inline style is what keeps an `initial={{ x }}` (or
 * any transform-type initial/animate) from being mistaken for the base.
 *
 * Returns `''` when the prop is not a string or carries no transform.
 *
 * @param style The component's `style` prop.
 * @returns The user's `transform` value, or `''`.
 * @example
 * ```ts
 * extractTransform('opacity: 0.5; transform: translateX(10px) scale(2)')
 * // => 'translateX(10px) scale(2)'
 * extractTransform('color: red') // => ''
 * extractTransform({ color: 'red' }) // => '' (non-string)
 * ```
 */
export const extractTransform = (style: unknown): string => {
    if (typeof style !== 'string') {
        if (!isMotionStyleObject(style)) return ''
        const transform = resolveStyleValue(style.transform)
        return transform == null ? '' : String(transform)
    }
    return parseStyleString(style).transform ?? ''
}

/**
 * Serialize a string or object-form Motion style prop into inline CSS.
 *
 * @param style The consumer-provided style prop.
 * @param transformTemplate Optional callback that receives the latest
 *   transform-related values and generated transform string, then returns the
 *   final CSS transform string for object-form styles.
 * @returns Inline CSS suitable for Svelte's `style` attribute.
 * @example
 * ```ts
 * serializeMotionStyle({ x: 24, opacity: 0.5 })
 * // => 'opacity: 0.5; transform: translateX(24px)'
 * ```
 */
export const serializeMotionStyle = (
    style: string | MotionStyle | null | undefined,
    transformTemplate?: TransformTemplate
): string => {
    if (typeof style === 'string') return style
    if (!isMotionStyleObject(style)) {
        if (!transformTemplate) return ''
        return mergeInlineStyles('', null, null, transformTemplate)
    }
    return mergeInlineStyles('', resolveMotionStyle(style), null, transformTemplate)
}

/**
 * Collect MotionValue entries from object-form style props.
 *
 * @param style The consumer-provided style prop.
 * @returns A map of style keys to MotionValues, or `undefined` when no live
 *   style values are present.
 */
export const collectMotionStyleValues = (
    style: unknown
): Record<string, MotionValue> | undefined => {
    if (!isMotionStyleObject(style)) return undefined

    const values: Record<string, MotionValue> = {}
    for (const [key, value] of Object.entries(style)) {
        if (isMotionValue(value)) {
            values[key] = value as MotionValue
        }
    }

    return Object.keys(values).length ? values : undefined
}

/**
 * Applies object-form style MotionValues while honoring `transformTemplate`.
 *
 * `motion-dom`'s `styleEffect` is used directly for the common path, but it
 * doesn't accept a per-component transform template. This helper mirrors its
 * behavior for templated styles by resolving the whole object on each value
 * change and serializing through the same transform builder as SSR.
 *
 * @param element Element receiving inline style updates.
 * @param style Object-form style prop to observe.
 * @param transformTemplate Optional transform template callback.
 * @returns Cleanup function, or `undefined` when no MotionValues are present.
 * @example
 * ```ts
 * const cleanup = applyMotionStyleEffect(element, { x }, ({ x }, generated) =>
 *     `translateY(${x}) ${generated}`
 * )
 * cleanup?.()
 * ```
 */
export const applyMotionStyleEffect = (
    element: HTMLElement,
    style: unknown,
    transformTemplate?: TransformTemplate
): (() => void) | undefined => {
    const values = collectMotionStyleValues(style)
    if (!values || !isMotionStyleObject(style)) return undefined

    const apply = () => {
        element.setAttribute(
            'style',
            mergeInlineStyles(
                element.getAttribute('style') ?? '',
                resolveMotionStyle(style),
                null,
                transformTemplate
            )
        )
    }

    let microtaskQueued = false
    let rafQueued = false

    const applyAfterOtherSubscribers = () => {
        apply()
        if (!microtaskQueued) {
            microtaskQueued = true
            queueMicrotask(() => {
                microtaskQueued = false
                apply()
            })
        }
        if (typeof requestAnimationFrame === 'function' && !rafQueued) {
            rafQueued = true
            requestAnimationFrame(() => {
                rafQueued = false
                apply()
            })
        }
    }

    applyAfterOtherSubscribers()

    const cleanups = Object.values(values).map((value) =>
        value.on('change', applyAfterOtherSubscribers)
    )
    return () => {
        for (const cleanup of cleanups) cleanup()
    }
}

const isMotionStyleObject = (style: unknown): style is MotionStyle =>
    !!style && typeof style === 'object' && !Array.isArray(style)

const resolveMotionStyle = (style: MotionStyle): Record<string, unknown> => {
    const resolved: Record<string, unknown> = {}

    for (const [key, value] of Object.entries(style)) {
        resolved[key] = resolveStyleValue(value)
    }

    return resolved
}

const resolveStyleValue = (value: MotionStyleValue): string | number | null | undefined => {
    if (isMotionStyleMotionValue(value)) return value.get()
    return value
}

const isMotionStyleMotionValue = (value: MotionStyleValue): value is MotionStyleMotionValue =>
    !!value && typeof value === 'object' && 'get' in value && typeof value.get === 'function'

const parseStyleString = (style: string): Record<string, string> => {
    const out: Record<string, string> = {}
    style
        .split(';')
        .map((s) => s.trim())
        .filter(Boolean)
        .forEach((decl) => {
            const idx = decl.indexOf(':')
            if (idx === -1) return
            const prop = decl.slice(0, idx).trim()
            const value = decl.slice(idx + 1).trim()
            if (prop) out[prop] = value
        })
    return out
}

const stringifyStyleObject = (obj: Record<string, string>): string =>
    Object.entries(obj)
        .map(([k, v]) => `${k}: ${v}`)
        .join('; ')

const toKebabCase = (s: string): string => s.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`)
