<script lang="ts">
    import { page } from '$app/state'
    import { resolve } from '$app/paths'
    import { AnimatePresence, motion } from '$lib'
    import { onMount } from 'svelte'
    import '../boundary-teardown/demo.css'

    let visible = $state(true)
    let leading = $state('unitless')
    let grow = $state(page.url.searchParams.get('grow') === 'true')
    let completed = $state(0)
    let ready = $state(false)
    const inline = page.url.searchParams.get('inline') === 'true'
    const idRule = page.url.searchParams.get('idRule') === 'true'

    onMount(() => {
        ready = true
    })

    function reset() {
        visible = true
        completed = 0
    }
</script>

<svelte:head><title>Exit typography and inheritance</title></svelte:head>

<main class="teardown-lab typography-lab">
    <header class="lab-header">
        <a class="back-link" href={resolve('/')}>← All demos</a>
        <p class="eyebrow">Exit lab / typography</p>
        <h1>Keep the rhythm.</h1>
        <p class="lede">Different text sizes. The same inheritance through an exit.</p>
        <p class="explanation">
            The caption, title, and nested text share a line height. A fade should keep their
            spacing. When the text grows, a unitless line height should grow with it—even for
            captions generated by CSS.
        </p>
    </header>
    <section class="demo-panel" aria-label="Exit typography demo">
        <div class="panel-heading">
            <h2>Watch the text, not just the card</h2>
            <span class="status"
                >{visible ? 'Ready to fade' : completed ? 'Exit complete' : 'Exiting'}</span
            >
        </div>
        <div class="typography-stage">
            <AnimatePresence initial={false} onExitComplete={() => completed++}>
                {#if visible}
                    <motion.div
                        key="typography"
                        id="typography-card"
                        class="typography-card"
                        data-leading={idRule ? 'id' : leading}
                        style={inline ? { lineHeight: 1.5 } : undefined}
                        exit={{ opacity: 0, fontSize: grow ? '32px' : '16px' }}
                        transition={{ duration: 1.8, ease: 'linear' }}
                    >
                        <strong class="typography-title"
                            >Room to breathe <span class="nested-text"
                                >Nested text keeps its rhythm.</span
                            ></strong
                        >
                        <span class="typography-description"
                            >A smooth goodbye, with every line in place.</span
                        >
                    </motion.div>
                {/if}
            </AnimatePresence>
        </div>
        <div class="demo-controls">
            <button
                id="fade"
                class="primary"
                disabled={!visible || !ready}
                onclick={() => (visible = false)}>{grow ? 'Fade and grow' : 'Fade out'}</button
            >
            <button id="reset" disabled={!ready} onclick={reset}>Reset</button>
            <label
                ><input type="checkbox" bind:checked={grow} disabled={!visible || !ready} /> Grow text
                during exit</label
            >
        </div>
        <div class="demo-readout">
            <label
                >Line height
                <select bind:value={leading} disabled={!visible || !ready}>
                    <option value="unitless">Unitless: 1.5</option>
                    <option value="normal">Normal</option>
                    <option value="length">Fixed: 24px</option>
                    <option value="percentage">Percentage: 150%</option>
                    <option value="variable">CSS variable: 1.5</option>
                    <option value="inherit">Explicit inherit</option>
                </select>
            </label>
            <p>Completed exits: <output id="completed">{completed}</output></p>
        </div>
        <p class="mode-note">
            Reset between comparisons. Fixed line heights stay fixed; unitless values scale with
            each text size.
        </p>
    </section>
</main>

<style>
    .typography-stage {
        display: grid;
        place-items: center;
        min-height: 400px;
        padding: 30px;
        line-height: 1.5;
        background: radial-gradient(ellipse at center, #242c48, #111722 80%);
    }
    :global(.typography-lab .typography-card) {
        --leading: 1.5;
        display: flex;
        flex-direction: column;
        justify-content: center;
        width: min(420px, 100%);
        min-height: 280px;
        padding: 28px;
        border-radius: 16px;
        background: #4064d9;
        color: white;
        font-size: 16px;
        line-height: 1.5;
    }
    :global(.typography-card[data-leading='normal']) {
        line-height: normal;
    }
    :global(.typography-card[data-leading='length']) {
        line-height: 24px;
    }
    :global(.typography-card[data-leading='percentage']) {
        line-height: 150%;
    }
    :global(.typography-card[data-leading='variable']) {
        line-height: var(--leading);
    }
    :global(.typography-card[data-leading='inherit']),
    :global(.typography-card[data-leading='id']) {
        line-height: inherit;
    }
    :global(#typography-card[data-leading='id']) {
        line-height: 1.75;
    }
    :global(.typography-card::before),
    :global(.typography-card::after) {
        display: block;
        font-size: 0.625em;
        letter-spacing: 0.08em;
        text-transform: uppercase;
    }
    :global(.typography-card::before) {
        content: 'A CSS caption';
    }
    :global(.typography-card::after) {
        content: 'A CSS sign-off';
        margin-top: 16px;
    }
    .typography-title {
        font-size: 2em;
    }
    .nested-text {
        display: block;
        font-size: 0.5em;
        font-weight: 400;
    }
    .typography-description {
        margin-top: 12px;
        font-size: 0.8em;
    }
    .demo-controls label {
        color: #b0bdd3;
        font-size: 0.8rem;
    }
</style>
